
version: "3.7"

services:

  app:
    build: ./
    container_name: WaProj_API
    command: yarn run dev
    user: root
    networks:
      - default
    ports:
      - 3000:3000
    #volumes:
    #  - ./:/home/node/WaProj_API/
    depends_on:
     - db
    links:
     - db

  db:
    image: postgres:latest
    container_name: WaProj_DB
    environment:
      POSTGRES_USER: postgres # default
      POSTGRES_PASSWORD: password # password sample
      POSTGRES_DB: WaProject_DB # database name sample
    user: root
    networks:
      - default
    #volumes:
    #  - ./.docker/docker_containers/postgresql/:/var/lib/postgresql/
    ports:
      - 5432:5432

networks:
  default:
    driver: bridge
